// The "siv_conversations" collection — one document per SIV conversation.
//
// Each runtime gets its OWN collection. This is the first one (SIV Method).
// When we add the next runtime later we create a sibling model/collection
// (e.g. ved_conversations) using this same pattern.
import { mongoose } from '../db.js';
import { config } from '../config.js';

const messageSchema = new mongoose.Schema(
  {
    role: { type: String, enum: ['user', 'assistant', 'system'], required: true },
    content: { type: String, required: true },
    at: { type: Date, default: Date.now },
  },
  { _id: false }
);

const sivConversationSchema = new mongoose.Schema(
  {
    // Whose conversation this is — Google id, matches User.googleId.
    userId: { type: String, required: true, index: true },
    email: { type: String, default: '' },

    // Constant for this collection, but stored so every document is
    // self-describing and queries across runtimes stay uniform.
    runtime: { type: String, default: 'siv', index: true },

    // Groups all turns of a single sitting. Generated by the client.
    sessionId: { type: String, required: true },

    messages: { type: [messageSchema], default: [] },

    // The final SIV "thinking artefact" JSON, once the conversation completes.
    artefact: { type: mongoose.Schema.Types.Mixed, default: null },
    status: { type: String, enum: ['active', 'complete'], default: 'active' },

    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now },

    // --- 30-day auto-delete ---
    // MongoDB's TTL monitor deletes a document once `expiresAt` is in the past
    // (expireAfterSeconds: 0 means "delete exactly at expiresAt").
    // We push this date forward on every save, so the 30 days count from the
    // LAST activity, not from creation.
    expiresAt: { type: Date, required: true },
  },
  {
    collection: 'siv_conversations',
    timestamps: false,
  }
);

// One conversation per (user, session).
sivConversationSchema.index({ userId: 1, sessionId: 1 }, { unique: true });
// The TTL index that powers auto-expiry.
sivConversationSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });

sivConversationSchema.methods.bumpExpiry = function () {
  const ms = config.conversationTtlDays * 24 * 60 * 60 * 1000;
  this.expiresAt = new Date(Date.now() + ms);
};

export const SivConversation = mongoose.model('SivConversation', sivConversationSchema);
