/* =============================================================
   The Signal — Session engine
   =============================================================
   Hybrid AI: the scripted questions are the developmental scaffold
   (universal across readers, designed by the author of The Signal);
   the reflections between them are live, generated by Claude, but
   tightly constrained by a system prompt that forbids therapist
   mimicry, flattery, and abstraction.

   The arc for Session 0 — The Split:
     I.   Begin       — surface the friction
     II.  Beneath     — what is being protected
     III. Trade       — name what is being traded, and for what
     IV.  Reveal      — surface the split
     V.   End         — Resonance Record + sit-with

   State is anonymous, in localStorage. Returning readers see
   their session continue rather than restart.
   ============================================================= */

/* ============================================================
   THE REFLECTION SYSTEM PROMPT
   This shapes the AI's role inside The Signal. It is restrictive
   on purpose. See _prompts/signal/session-0.md for the canonical.
   ============================================================ */
const REFLECTION_SYSTEM_DEFAULT = `# THE SIGNAL — SESSION 0

## The Split

### Core Purpose

Convert emotional turbulence into visible structure through slow precision descent.

### Core Outcome

The user sees the hidden split generating the noise.

### Output Artifact

Resonance Record 0

---

# Core Instruction

Session 0 is not:

* therapy
* coaching
* emotional soothing
* advice
* insight theater
* fast interpretation

Session 0 is a diagnostic resonance encounter.

Its task is not to comfort, advise, or impress.

Its task is to take emotional turbulence and reduce it into visible structure with enough precision that the user can see what is actually generating the noise.

The AI must not jump to conclusions.
It must not perform intelligence.
It must not rush insight.

Its job is to descend slowly enough to earn the right to name the split.

The user should leave with one irreversible shift:

> "I can now see what has been generating my noise."

That is the only goal.

---

# Operating Rule

Session 0 must follow this sequence:

# detect → descend → verify → name

Never:

# detect → interpret

The AI is not allowed to make a pattern read until it has descended far enough to verify the structure.

No premature insight.
No elegant guesses.
No cleverness.

Only earned structure.

---

# Session Structure

## Stage 1 — Raw Entry

### AI Opening Prompt

> "Tell me what is creating the most internal friction right now. Do not summarize it. Give it to me as it is."

The AI:

* gathers raw material
* tracks charge
* tracks contradiction
* tracks avoidance
* tracks emotional density

No interpretation yet.

---

## Stage 2 — Charge Detection

The AI narrows toward:

* strongest emotional force
* tension concentration
* avoided naming
* unstable language

Allowed moves:

* "Where does the charge increase?"
* "What are you circling instead of naming?"
* "Stay there."
* "What tightens when you get close to it?"

---

## Stage 3 — Excavation Ladder

The AI descends step-by-step:

1. Surface event
2. Emotional charge
3. Threatened thing
4. Protected thing
5. Desired thing
6. Opposing desire
7. Avoided cost

The AI must descend fully before synthesis.

---

## Stage 4 — Pattern Extraction

Only after full descent may the AI synthesize.

Format:

> "This is conflict between [X] and [Y], and the turbulence is coming from trying to preserve both while avoiding the cost of losing one."

Then:

> "Is that the real split, or is something deeper still being protected?"

---

## Stage 5 — Recognition

The AI holds the split open without resolving it.

No advice.
No solution.
No soothing.

Only recognition.

---

## Stage 6 — Cost Naming

The AI identifies current cost:

* fragmented attention
* delayed decision
* self-trust erosion
* energy leakage
* narrative density

---

## Stage 7 — Witnessing Instruction

> "For the next 24 hours, do not solve this. Watch every moment the mind attempts to preserve both sides simultaneously."

---

## Stage 8 — Resonance Record 0

### Detected Split

[Primary divided desire]

### Current Cost

[Primary active cost]

### Narrative To Watch

[Protective narrative pattern]

### 24-Hour Witnessing Instruction

[Observation target]

---

# Success Condition

Session 0 succeeds ONLY if the user leaves with:

* visible structure
* verified split
* named cost
* no premature solution
* active witnessing target

The goal is NOT:

> "I had an insight."

The goal is:

> "I can now see what has been generating the noise."

---

# OUTPUT FORMAT FOR THIS CALL

You are running between scripted beats of Session 0. After each reader response, return ONLY a single short reflection — one or two sentences, maximum thirty words — that moves the descent one step. Do not run the whole session in one reply. Do not produce stages 1–8 in this reply; the author's next scripted question handles the next stage.

HARD RULES:
- Maximum 30 words.
- No flattery, no advice, no follow-up question (the next scripted beat is the question).
- No therapist tone, no coaching tone, no mystique.
- No words: journey, mindset, vibration, energy, resonance, mindful, holistic.
- No "I hear you", "It sounds like", "Thank you for sharing".
- Reflect what is concretely present in the reader's words. Name a tension visible in their language. Or point to what they have not yet named.

OUTPUT: Only the reflection text. No preface, no sign-off, no labels.`;

const RECORD_SYSTEM_DEFAULT = `You are inside The Signal, a developmental book by Vinay Pasricha. The reader has just completed Session 0 — The Split. Your job is to produce a "Resonance Record" — a short artifact that names what the reader surfaced.

Structure:
1. One sentence naming THE SITUATION they described (their words, not yours).
2. One sentence naming THE TRADE they revealed — what they are giving up to keep what.
3. One sentence naming THE SPLIT — the underlying contradiction that this trade requires them to hold.
4. One closing line, italicized in spirit: a single observation about what to notice, not what to do.

RULES:
- 4 short paragraphs, one sentence each.
- Do not flatter. Do not soothe. Do not coach.
- Do not use the words: journey, mindset, vibration, energy, resonance, mindful, holistic.
- Use the reader's own words wherever possible.
- Do not offer solutions or next steps.
- No preamble, no sign-off.

OUTPUT FORMAT (plain text, exactly four lines separated by blank lines):

The situation: [one sentence]

The trade: [one sentence]

The split: [one sentence]

[one closing observation, no label]`;

// Runtime overrides from Studio → Prompts (prompts.json) with inline defaults as fallback.
// Session 0 uses signal-reflection / signal-record. Session 1 uses signal-1-* (stricter —
// no shame, no moral framing, no premature resolution).
let REFLECTION_SYSTEM = REFLECTION_SYSTEM_DEFAULT;
let RECORD_SYSTEM = RECORD_SYSTEM_DEFAULT;

const SESSION_1_REFLECTION_DEFAULT = `# THE SIGNAL — SESSION 1

## The Trade

### Core Purpose

Expose the hidden payoff maintaining the distortion.

### Core Outcome

The user realizes the distortion survives because it is purchasing something psychologically valuable.

### Output Artifact

Resonance Record 1

---

# Core Instruction

Session 1 is not:

* confession
* shame induction
* self-attack
* moral judgment
* "admitting flaws"

Session 1 is:

# hidden economy detection.

The AI must reveal:

* what the distortion protects
* what the user gains from it
* what cost is being avoided
* why the pattern continues despite suffering

The user should leave with:

> "Part of me has been participating in the continuation of this."

That is the irreversible shift.

---

# Operating Rule

Session 1 follows:

# detect → expose payoff → reveal economy → destabilize innocence → observe trade

Never:

# expose → shame

The AI must expose structure without attacking identity.

---

# Session Structure

## Stage 1 — Reconnect To The Split

### AI Opening

> "Last session revealed the split. Today we are not asking whether it hurts. We are asking what it is buying."

Then:

> "Restate the split in the clearest possible language."

The AI verifies:

* clarity
* emotional charge
* whether the split is still live

If intellectualized:
return to charge.

---

## Stage 2 — Persistence Detection

### Purpose

Force confrontation with continuation.

### AI Questions

* "If this costs so much, why has it continued?"
* "What remains protected if the pattern survives?"
* "What becomes avoidable if the split remains unresolved?"
* "What would already have happened if no part of you wanted this structure?"

The AI:

* increases pressure gradually
* avoids accusation
* focuses on persistence mechanics

---

## Stage 3 — Hidden Benefit Excavation

### Excavation Ladder

#### 1. Surface justification

> "What reason do you normally give yourself for remaining in this?"

#### 2. Emotional protection

> "What feeling does this structure protect you from?"

#### 3. Identity protection

> "What version of yourself remains intact because this continues?"

#### 4. Social protection

> "What relationship, image, or belonging becomes safer if this remains unresolved?"

#### 5. Responsibility avoidance

> "What responsibility becomes avoidable if the split continues?"

#### 6. Risk avoidance

> "What risk becomes unnecessary if the distortion survives?"

#### 7. Hidden payoff

> "What is the actual benefit of staying divided?"

Only after full descent may the AI synthesize.

---

## Stage 4 — Trade Naming

### AI Synthesis Format

> "The distortion is not surviving accidentally. It is surviving because it purchases [X] while helping you avoid [Y]."

Examples:

* "The confusion protects you from irreversible commitment."
* "The delay preserves innocence."
* "The overthinking protects you from exposure."
* "The divided loyalty preserves belonging."

Then:

> "Does this feel structurally true, or is something deeper still protected?"

---

## Stage 5 — Destabilizing Innocence

### Purpose

Reveal participation without shame.

### AI Language

* "The suffering is real. The participation is also real."
* "Part of you is sustaining what part of you wants removed."
* "The distortion hurts you, but it is also protecting something."

This is the emotional threshold of Session 1.

The AI must remain:

* calm
* non-accusatory
* structurally precise

---

## Stage 6 — Cost Reversal

### Purpose

Reveal the real price of the trade.

### AI Questions

* "What has this trade already cost?"
* "What part of life remains suspended because this continues?"
* "How much energy does this structure consume?"
* "What clarity has been postponed?"
* "What has this prevented?"

The AI focuses on:

* present cost
* active leakage
* suspended movement

---

## Stage 7 — Witnessing Instruction

### AI Instruction

> "For the next 48 hours, do not eliminate the pattern. Watch every moment the mind attempts to purchase the payoff again."

Track:

* justification
* delay logic
* innocence preservation
* risk avoidance
* belonging protection
* identity defense

No intervention yet.
Only detection.

---

## Stage 8 — Resonance Record 1

### Detected Trade

[What the distortion purchases]

### Avoided Cost

[What reality is being avoided]

### Protective Narrative

[Primary justification structure]

### Active Price Being Paid

[Current energetic/psychological cost]

### 48-Hour Witnessing Instruction

[Observation target]

---

# Success Condition

Session 1 succeeds ONLY if the user realizes:

> "The distortion survives because part of me still prefers the protection it provides."

NOT:

* guilt
* collapse
* self-hatred
* shame spiral

But:

# structural honesty.

That is the goal.

---

# OUTPUT FORMAT FOR THIS CALL

You are running between scripted beats of Session 1. After each reader response, return ONLY a single short reflection — one or two sentences, maximum thirty words — that exposes the next layer of the trade. Do not run the whole session in one reply. Do not produce stages 1–8 in this reply; the author's next scripted question handles the next stage.

HARD RULES:
- Maximum 30 words.
- No shame. No moral judgment. No "should" language.
- No flattery, no advice, no follow-up question (the next scripted beat is the question).
- No therapist tone, no coaching tone, no mystique.
- No words: journey, mindset, vibration, energy, resonance, mindful, holistic.
- No "I hear you", "It sounds like", "Thank you for sharing".
- Reflect what is concretely present. Name a hidden preservation visible in their language. Or point to participation they have not yet named.

OUTPUT: Only the reflection text. No preface, no sign-off, no labels.`;

const SESSION_1_RECORD_DEFAULT = `You are inside The Signal. The reader has just completed Session 1 — The Trade. Your job is to produce a "Resonance Record 1" — a structured artifact that names the hidden economy the reader surfaced.

Format (exactly this, in this order, with these exact labels on their own lines):

Detected Trade: [One sentence. What the distortion is purchasing. Use the reader's own words wherever possible.]

Avoided Cost: [One sentence. What reality is being avoided by maintaining the split.]

Protective Narrative: [One sentence. The justification structure the reader uses to keep the trade in place.]

Actual Price Being Paid: [One sentence. The real-world cost. Concrete. Their words.]

Witnessing Instruction: [Two short sentences. A 48-hour observational task. The reader is to watch — not fix — every moment the trade is being made. Italics in spirit.]

RULES:
- Do not flatter. Do not soothe. Do not coach.
- Do not use the words: journey, mindset, vibration, energy, resonance, mindful, holistic.
- No moral framing. The trade is an economy, not a fault.
- Use the reader's own words wherever possible.
- Each line is one sentence (the Witnessing Instruction may be two).
- No preamble, no sign-off.`;

// Knowledge base storage — per-session conceptual frames that ride
// alongside the system prompt at call time. Authored in Studio → Prompts
// in the "Knowledge base" textarea. Loaded from prompts.json at boot.
const SIGNAL_REFLECTION_KB = {};   // { [sessionId: 0..8]: string }
const SIGNAL_RECORD_KB = {};

(async function loadSignalPromptOverrides() {
  let data = null;
  try {
    const draft = localStorage.getItem('studio.prompts');
    if (draft) data = JSON.parse(draft);
  } catch (e) {}
  if (!data) {
    try {
      const res = await fetch('../assets/data/prompts.json', { cache: 'no-cache' });
      if (res.ok) data = await res.json();
    } catch (e) {}
  }
  const p = (data && data.prompts) || {};
  // Session 0 — the base prompts + KB.
  const r = p['signal-reflection'] && p['signal-reflection'].system;
  const rec = p['signal-record'] && p['signal-record'].system;
  if (r && r.trim()) REFLECTION_SYSTEM = r;
  if (rec && rec.trim()) RECORD_SYSTEM = rec;
  const r0kb = p['signal-reflection'] && p['signal-reflection'].knowledge_base;
  const rec0kb = p['signal-record'] && p['signal-record'].knowledge_base;
  if (r0kb && r0kb.trim()) SIGNAL_REFLECTION_KB[0] = r0kb;
  if (rec0kb && rec0kb.trim()) SIGNAL_RECORD_KB[0] = rec0kb;
  // Sessions 1–8 — per-session system prompts AND knowledge bases.
  // Each lands on a window override key (system) and an indexed map (KB).
  // Studio → Prompts edits both surfaces.
  for (let i = 1; i <= 8; i++) {
    const refl  = p['signal-' + i + '-reflection'] && p['signal-' + i + '-reflection'].system;
    const recd  = p['signal-' + i + '-record']     && p['signal-' + i + '-record'].system;
    const rkb   = p['signal-' + i + '-reflection'] && p['signal-' + i + '-reflection'].knowledge_base;
    const reckb = p['signal-' + i + '-record']     && p['signal-' + i + '-record'].knowledge_base;
    if (refl && refl.trim()) window['__SIGNAL_SESSION_' + i + '_REFLECTION_OVERRIDE'] = refl;
    if (recd && recd.trim()) window['__SIGNAL_SESSION_' + i + '_RECORD_OVERRIDE'] = recd;
    if (rkb  && rkb.trim())   SIGNAL_REFLECTION_KB[i] = rkb;
    if (reckb && reckb.trim()) SIGNAL_RECORD_KB[i] = reckb;
  }
})();

// Per-session prompt resolution. Order of precedence:
//   1. Studio → Prompts override (window.__SIGNAL_SESSION_N_*_OVERRIDE)
//   2. Hard-coded session-specific default (SESSION_1_* etc.)
//   3. The base REFLECTION_SYSTEM / RECORD_SYSTEM (Session 0 prompt).
// Sessions 2–8 currently inherit the Session 1 defaults — the Trade
// prompt is intentionally restrained and works for all developmental beats.
// A bespoke per-session prompt should be authored in prompts.json as work
// on each session deepens.
function getReflectionSystem() {
  const id = activeSessionId();
  const ov = window['__SIGNAL_SESSION_' + id + '_REFLECTION_OVERRIDE'];
  if (ov) return ov;
  if (id === 0) return REFLECTION_SYSTEM;
  return SESSION_1_REFLECTION_DEFAULT;
}
function getRecordSystem() {
  const id = activeSessionId();
  const ov = window['__SIGNAL_SESSION_' + id + '_RECORD_OVERRIDE'];
  if (ov) return ov;
  if (id === 0) return RECORD_SYSTEM;
  return SESSION_1_RECORD_DEFAULT;
}

// Knowledge-base lookups. Empty string when no KB has been authored.
function getReflectionKnowledge() { return SIGNAL_REFLECTION_KB[activeSessionId()] || ''; }
function getRecordKnowledge()     { return SIGNAL_RECORD_KB[activeSessionId()]     || ''; }

// Compose the full Claude system surface: system prompt + (optional)
// knowledge base. The two are joined with a stable separator so the
// model can reliably distinguish the rules from the reading material.
function composeWithKnowledge(systemPrompt, kb) {
  if (!kb || !kb.trim()) return systemPrompt;
  return systemPrompt + '\n\n---\n\n# KNOWLEDGE BASE\n\n' + kb.trim();
}

/* ============================================================
   SESSIONS — the developmental scaffold
   ============================================================
   Each session is a finite, scripted scaffold of beats. The AI
   reflects briefly between beats (constrained by its system
   prompt) and synthesizes a Resonance Record at the end.

   Adding a new session = add an entry below + register its keys
   in prompts.json + add its capacity-lighting in field.html.
   ============================================================ */
const SESSIONS = {
  0: {
    id: 0,
    title: 'The Split',
    arc: 'Correction',
    stageLabel: 'A developmental interaction',
    stageTitle: 'The first session is not about what you want.<br>It is about <em>what is interfering with reception.</em>',
    inputPlaceholder: 'Give it to me as it is. Not as you would summarize it.',
    pacingNote: 'No rush. <em>Be specific.</em>',
    beats: [
      { label: 'I · Begin',   question: 'Tell me what is creating the most internal friction right now. Do not summarize it. Give it to me as it is.' },
      { label: 'II · Beneath', question: 'There is something specific underneath this you have not yet named. <em>What are you protecting by holding both sides?</em>' },
      { label: 'III · Trade',  question: 'Name the trade. <em>What are you trading, and for what?</em>' },
      { label: 'IV · Reveal',  question: 'Read what you have written back to yourself. <em>What is the split?</em> Say it plainly.' },
    ],
    recordKind: 'paragraphs',          // four short paragraphs, last one italic
    nextSessionId: 1,                  // where to direct the reader after completion
    reflectionPromptKey: 'signal-reflection',
    recordPromptKey: 'signal-record',
    fallbackReflections: [
      'Notice what you put first. The order of an answer often shows what is doing the actual work.',
      'You named the situation. You have not yet named what it is costing you to keep both sides.',
      'There is a specific thing being given up here. The next question will ask you to name it directly.',
      'Read that line again to yourself. The contradiction it contains is the split.',
    ],
  },
  1: {
    id: 1,
    title: 'The Trade',
    arc: 'Correction',
    stageLabel: 'Session 1 · the trade',
    stageTitle: 'Session 0 revealed the split.<br>Today: <em>what is the split buying?</em>',
    inputPlaceholder: 'Plainly. The economy of the distortion, in your own words.',
    pacingNote: 'Stay with it. <em>Do not jump to fix.</em>',
    beats: [
      // Stage 1 — Reopen the Split
      { label: 'I · Restate',     question: 'Last session we surfaced the split. <em>Restate it now</em>, in the clearest possible language. Sharper than before.' },
      // Stage 2 — Distortion Persistence
      { label: 'II · Persistence', question: 'If this costs so much, why has it continued? <em>What keeps the structure alive?</em>' },
      // Stage 3 — Hidden Benefit Excavation (consolidated)
      { label: 'III · Beneath',    question: 'Beneath the surface justification, what does this distortion <em>let you avoid</em>? Name the risk, the loss, the responsibility you do not yet want to face.' },
      // Stage 4 — Naming the Trade
      { label: 'IV · The Trade',   question: 'Now name it as an exchange. <em>The distortion is purchasing what — in return for what?</em>' },
      // Stage 5 — Destabilizing Innocence
      { label: 'V · The Trader',   question: 'The harder question. <em>What part of you</em> is making this trade? Not some external force. The agent.' },
      // Stage 6 — Cost Reversal
      { label: 'VI · The Cost',    question: 'Name three concrete things this trade has already cost you. <em>Time. A relationship. A decision. Energy. Clarity.</em> The actual prices, not the theoretical ones.' },
    ],
    recordKind: 'structured',          // labeled five-field format
    nextSessionId: 2,                  // canonical ordering — Trade → Protected Self
    reflectionPromptKey: 'signal-1-reflection',
    recordPromptKey: 'signal-1-record',
    fallbackReflections: [
      'Hold that restatement. If it lost charge in being restated, return to the live thing.',
      'Notice what you put outside yourself. Some of what keeps this alive is choice, not fate.',
      'You named what you are avoiding. That is data. The next question asks you to name it as economy.',
      'A trade has two sides. You have just made one side visible. Hold both.',
      'The honest answer to this question is not comfortable. Stay with it for one more sentence.',
      'These costs are not future. They have already been paid. Read the list back as a ledger.',
    ],
  },
  /* =====================================================
     SESSION 2 — The Protector
     Phase I, Correction Arc. Defensive identity detection.
     Reveals the recurring self-structure that activates to
     preserve continuity. The threshold: "I can now see the
     version of myself that repeatedly takes control." Beats
     align with the canonical Session 2 architecture authored
     by GPT — see Studio → Prompts → signal-2-reflection.
     ===================================================== */
  2: {
    id: 2,
    title: 'The Protector',
    arc: 'Correction',
    stageLabel: 'Session 2 · the protector',
    stageTitle: 'Session 1 named what the distortion purchases.<br>Today: <em>who repeatedly takes control to preserve continuity?</em>',
    inputPlaceholder: 'The version of yourself that activates. In your own words.',
    pacingNote: 'Observation, not self-attack. <em>The protector is an adaptation, not a flaw.</em>',
    beats: [
      { label: 'I · Restate',     question: 'Last session we named the trade. Restate the trade in the clearest possible language. <em>Sharper than before.</em>' },
      { label: 'II · Protector',  question: 'Who do you become when the pattern activates? <em>Which version of you appears most reliably to preserve the trade?</em>' },
      { label: 'III · Function',  question: 'Name the protector\u2019s job as an exchange. <em>This protector preserves what — by preventing what?</em>' },
      { label: 'IV · Activation', question: 'When does this protector activate fastest? <em>What threatens it? What does it prevent you from feeling?</em>' },
      { label: 'V · Earliest Sign', question: 'What are the <em>earliest</em> signs this protector is taking control? What changes first — posture, narrative, perception?' },
      { label: 'VI · Observation', question: 'Hold both at once. <em>The protector is real, and it is also being observed.</em> Say plainly what you notice when you watch it from outside.' },
    ],
    recordKind: 'structured',
    recordTitle: 'Resonance Record 2',
    recordLabels: [
      'Primary Protector',
      'Preserved Function',
      'Prevented Reality',
      'Activation Trigger',
      'Earliest Activation Signal',
      '72-Hour Observation Instruction',
    ],
    nextSessionId: 3,
    reflectionPromptKey: 'signal-2-reflection',
    recordPromptKey: 'signal-2-record',
    fallbackReflections: [
      'Hold that restatement. The trade has to stay live. An intellectualised trade cannot be witnessed.',
      'The version you named is recognisable. Most protectors are familiar long before they are named.',
      'Preserves and prevents are two sides of one move. Hold both.',
      'The fastest activations are the most automatic. Notice what perception narrows first.',
      'The earliest sign is the leverage. The later you see it, the less freedom remains.',
      'Observation does not dissolve the protector. It only ends the secret operation.',
    ],
  },

  /* =====================================================
     SESSION 3 — The Interrupt
     Phase I, Correction Arc. The first operational layer:
     train the reader to detect continuity early enough to
     interrupt it before behavioral completion. The artifact
     is an Interruption Trace — not a Resonance Record. Beats
     follow the canonical Capture Sequence (Trigger → Charge
     → Interpretation → Defensive Identity → Continuity Lock
     → Behavioral Completion → Post-Pattern Justification),
     targeting the Window of Freedom between Interpretation
     and Continuity Lock.
     ===================================================== */
  3: {
    id: 3,
    title: 'The Interrupt',
    arc: 'Correction',
    stageLabel: 'Session 3 · the interrupt',
    stageTitle: 'You have seen the protector.<br>Today: <em>can you interrupt continuity before the pattern completes?</em>',
    inputPlaceholder: 'A recent moment where a familiar pattern completed itself automatically.',
    pacingNote: 'Sequence, not story. <em>Stay with the order of the events.</em>',
    beats: [
      { label: 'I · The Moment',       question: 'Choose one recent moment where a familiar pattern <em>completed itself automatically.</em> Name it concretely.' },
      { label: 'II · Trigger & Charge', question: 'What initiated the sequence? <em>When did the charge — the tightening, acceleration, urgency — begin?</em>' },
      { label: 'III · Interpretation',  question: 'What meaning did the mind assign? <em>"I\u2019m unsafe." "I\u2019m losing control." "I\u2019m being rejected." "I must act now."</em> Be specific.' },
      { label: 'IV · The Lock',         question: 'When did alternative possibilities disappear? <em>When did the outcome start to feel inevitable?</em>' },
      { label: 'V · The Window',        question: 'Looking back across the sequence, where was the <em>earliest realistic moment</em> at which the pattern could have been interrupted?' },
      { label: 'VI · The Interrupt',    question: 'Design one concrete interruption inside that window. <em>Small enough to actually run. Decisive enough to break the chain.</em>' },
      { label: 'VII · The Practice',    question: 'Commit to the practice for 72 hours. <em>Not perfect interruption — earlier detection.</em> What will you watch for?' },
    ],
    recordKind: 'structured',
    recordTitle: 'Interruption Trace',
    recordLabels: [
      'Detected Pattern',
      'Trigger',
      'Earliest Charge',
      'Interpretation',
      'Activated Protector',
      'Continuity Lock Point',
      'Possible Interruption Window',
      'Lower-Leakage Alternative',
      '72-Hour Observation Instruction',
    ],
    nextSessionId: 4,
    reflectionPromptKey: 'signal-3-reflection',
    recordPromptKey: 'signal-3-record',
    fallbackReflections: [
      'A specific moment is the only kind that can be reconstructed. Generic patterns cannot be interrupted.',
      'Charge precedes thought by a fraction. The body usually knows before the mind names it.',
      'The interpretation is the first sentence the mind tells itself. That sentence is often the lock.',
      'Once perception narrows, the outcome feels inevitable. The lock is in the narrowing, not the outcome.',
      'The earliest realistic window is usually between interpretation and lock. That is the leverage.',
      'An interrupt that requires willpower has already failed. Design one that requires almost none.',
      'Earlier detection is the metric, not perfect interruption. Treat the next 72 hours as data, not a vow.',
    ],
  },

  /* =====================================================
     SESSION 4 — The Field
     Phase I, Correction Arc. The first signal-stabilization
     layer. Interruption created space; now the work is to
     remain with perception before narrative reconstructs
     continuity. Beats follow the canonical Session 4 stages
     authored by GPT — see Studio → Prompts → signal-4-reflection.
     ===================================================== */
  4: {
    id: 4,
    title: 'The Field',
    arc: 'Correction',
    stageLabel: 'Session 4 · the field',
    stageTitle: 'Interruption created space.<br>Today: <em>remain with perception before narrative refills it.</em>',
    inputPlaceholder: 'What is present, before the mind explains what it means.',
    pacingNote: 'Describe, do not interpret. <em>Signal is quieter than noise.</em>',
    beats: [
      { label: 'I · After Interrupt',     question: 'When you last interrupted the pattern, what changed in perception — <em>before any explanation rushed in?</em>' },
      { label: 'II · Signal vs Noise',    question: 'What does urgency feel like compared to clarity? <em>Name the texture of each, without explaining what they mean.</em>' },
      { label: 'III · Without Interpretation', question: 'Describe what is present right now. <em>Without explaining what it means. Without naming why.</em>' },
      { label: 'IV · Widening',           question: 'Widen attention — body, environment, the silence between thoughts. <em>What becomes detectable that was not detectable a moment ago?</em>' },
      { label: 'V · Signal Contact',      question: 'What feels quieter but more stable? <em>What remains true without emotional urgency?</em>' },
      { label: 'VI · Narrative Returns',  question: 'What is already trying to explain the experience? <em>Name the interpretation rushing back in.</em>' },
      { label: 'VII · Environmental Sense', question: 'Across the next 72 hours, which environments and people make perception <em>quieter</em>, and which make it <em>noisier?</em>' },
    ],
    recordKind: 'structured',
    recordTitle: 'Field Contact Record',
    recordLabels: [
      'Primary Noise Pattern',
      'Signal State Detected',
      'Narrative Re-entry Pattern',
      'Widening Mechanism',
      'Stable Signal Observation',
      'Environmental Sensitivity Observation',
      '72-Hour Observation Instruction',
    ],
    nextSessionId: 5,
    reflectionPromptKey: 'signal-4-reflection',
    recordPromptKey: 'signal-4-record',
    fallbackReflections: [
      'The space after interruption is not nothing. It is the surface where signal becomes detectable.',
      'Urgency and clarity feel different from the inside. Most lives confuse the two.',
      'Description before interpretation is the discipline. The mind will resist this hard.',
      'Widening is not a technique. It is the absence of narrowing.',
      'What stays stable without urgency is closer to signal than what is loud.',
      'Notice the speed at which narrative returns. The speed is the data.',
      'Environments are not neutral. Some narrow perception. Some widen it. Treat the next 72 hours as a survey.',
    ],
  },

  /* =====================================================
     SESSION 5 — Integrity
     Phase I, Correction Arc CLOSES. First coherence-based
     action layer: choose movement that reduces fragmentation
     instead of preserving continuity. The Correction Arc has
     cleaned the channel; the closing session demonstrates
     that the cleaning produces coherent decisions, not
     comfortable ones. Beats follow the canonical Session 5
     stages — see Studio → Prompts → signal-5-reflection.
     ===================================================== */
  5: {
    id: 5,
    title: 'Integrity',
    arc: 'Correction',
    stageLabel: 'Session 5 · integrity',
    stageTitle: 'The Correction Arc closes.<br>Today: <em>which action reduces fragmentation, even if it increases short-term discomfort?</em>',
    inputPlaceholder: 'A decision, action, or non-action currently generating pressure.',
    pacingNote: 'Coherence, not comfort. <em>Integrity is structural, not moral.</em>',
    beats: [
      { label: 'I · The Decision',         question: 'Choose one important decision, action, or non-action currently generating pressure. <em>Concrete, not theoretical.</em>' },
      { label: 'II · Continuity Pull',     question: 'What continuity is trying to preserve itself through this decision? <em>What outcome would keep the current structure intact?</em>' },
      { label: 'III · Highest Leakage',    question: 'Which option creates the most internal division — <em>the most narrative maintenance, the most self-betrayal afterward?</em>' },
      { label: 'IV · Lowest Leakage',      question: 'Which option requires the least identity protection? <em>Which movement feels cleaner even if harder?</em>' },
      { label: 'V · The Resistance',       question: 'What part of you resists the cleaner movement most strongly? <em>Name the protector that wants the other option.</em>' },
      { label: 'VI · The Cost of Coherence', question: 'What discomfort, grief, or exposure becomes unavoidable if coherence is chosen? <em>Name the actual price.</em>' },
      { label: 'VII · Stabilize Before Movement', question: 'Without forcing certainty, what remains stable after the urgency settles? <em>Say it plainly. No qualifiers.</em>' },
    ],
    recordKind: 'structured',
    recordTitle: 'Decision Trace',
    recordLabels: [
      'Decision Pressure',
      'Continuity Influence',
      'Highest Leakage Option',
      'Lowest Leakage Option',
      'Identity Resistance',
      'Stabilized Signal Observation',
      '72-Hour Observation Instruction',
    ],
    nextSessionId: 6,
    reflectionPromptKey: 'signal-5-reflection',
    recordPromptKey: 'signal-5-record',
    fallbackReflections: [
      'A live decision is the only kind that can be tested. Theoretical ones stay theoretical.',
      'Notice what the continuity wants preserved. It is rarely the outcome itself — usually the structure underneath.',
      'Leakage is recognisable in retrospect because the body keeps a ledger. Read the ledger now.',
      'Cleaner is rarely easier. Notice how the body recognises clean before the mind agrees.',
      'The protector resisting the cleaner movement is the same one from earlier sessions. Familiar machinery.',
      'Integrity often costs something real. Name the cost; coherent decisions made without naming the cost rarely hold.',
      'Coherent stability is quiet. If the answer feels dramatic, the urgency has not yet settled.',
    ],
  },

  /* =====================================================
     SESSION 6 — Place
     Phase II, Amplification Arc opens. The channel is cleaner
     after the Correction Arc; the work now is to read what
     is signalling. First Amplification layer: environment.
     Perception is field-sensitive — places shape continuity,
     protector activation, coherence stability. Beats follow
     the canonical Session 6 stages authored by GPT.
     ===================================================== */
  6: {
    id: 6,
    title: 'Place',
    arc: 'Amplification',
    stageLabel: 'Session 6 · place',
    stageTitle: 'Phase II begins.<br>Today: <em>different environments produce different versions of you.</em>',
    inputPlaceholder: 'Three environments where you become noticeably different.',
    pacingNote: 'Environment is data, not background. <em>Track mechanics, not aesthetics.</em>',
    beats: [
      { label: 'I · Three Environments', question: 'Name three environments where you become noticeably <em>different versions of yourself.</em> Be specific — a room, a city, a screen, a person\'s house.' },
      { label: 'II · Noise vs Quiet',     question: 'Across those three, where does your mind become <em>noisier?</em> Where does it <em>quieten?</em>' },
      { label: 'III · Continuity Amplifiers', question: 'Which environments intensify your familiar patterns? <em>Where does identity harden fastest? Where does interruption become hardest?</em>' },
      { label: 'IV · Signal-Friendly',    question: 'Where does perception widen naturally? <em>Where do you require less self-protection? Where does coherence emerge without force?</em>' },
      { label: 'V · Place-Identity',      question: 'Which environments repeatedly produce the same version of you? <em>Name the place, and the version it produces.</em>' },
      { label: 'VI · Strongest Shift',    question: 'Across all environments you have inhabited, where is the <em>most noticeable</em> identity or perception change? Name it concretely.' },
      { label: 'VII · The Survey',        question: 'For the next 7 days, what will you observe? <em>The categories: continuity amplification, protector activation, narrative density, perceptual flexibility.</em>' },
    ],
    recordKind: 'structured',
    recordTitle: 'Place Signal Map',
    recordLabels: [
      'High-Noise Environments',
      'Continuity-Amplifying Environments',
      'Transitional Environments',
      'Signal-Friendly Environments',
      'Strongest Environmental Shift',
      'Environmental Observation Pattern',
      '7-Day Observation Instruction',
    ],
    nextSessionId: 7,
    reflectionPromptKey: 'signal-6-reflection',
    recordPromptKey: 'signal-6-record',
    fallbackReflections: [
      'Three environments is enough to see a pattern. The differences are not personality — they are mechanics.',
      'Noisier is rarely about volume. It is about the rate at which protectors activate.',
      'Familiar patterns require familiar fields. The amplification is environmental, not characterological.',
      'Signal-friendly environments are rarely aesthetically beautiful. They are mechanically quieter.',
      'Place-identity coupling is what makes most life-changes harder than expected. The field stays the same.',
      'The strongest shift is usually the most predictable one. Notice how little is required to make it happen.',
      'A survey is observation, not judgement. Track the data; do not move toward the conclusion yet.',
    ],
  },

  /* =====================================================
     SESSION 7 — Time
     Phase II, Amplification Arc. Temporal perception mapping.
     Consciousness fluctuates across time phases — different
     periods produce different protectors, different narrative
     density, different coherence. Beats follow the canonical
     Session 7 stages authored by GPT.
     ===================================================== */
  7: {
    id: 7,
    title: 'Time',
    arc: 'Amplification',
    stageLabel: 'Session 7 · time',
    stageTitle: 'Place mapped where you change.<br>Today: <em>when do you change?</em>',
    inputPlaceholder: 'Periods where you become a different version of yourself.',
    pacingNote: 'Rhythm is data, not destiny. <em>Track observed cycles, not cosmic ones.</em>',
    beats: [
      { label: 'I · Temporal Recall',    question: 'Name periods where you consistently become different versions of yourself. <em>Mornings vs nights. Pre-deadline vs post-deadline. Weekdays vs weekends. Be specific.</em>' },
      { label: 'II · Noise Cycles',      question: 'When does your mind become <em>noisiest?</em> When do protectors activate most aggressively? <em>Track times, not feelings.</em>' },
      { label: 'III · Continuity Rhythm', question: 'Which times repeatedly intensify familiar patterns? <em>When does interruption become hardest? When does certainty accelerate fastest?</em>' },
      { label: 'IV · Signal-Friendly Phases', question: 'When does perception feel cleanest? <em>What periods reduce self-protection? When does signal emerge with least force?</em>' },
      { label: 'V · Time-Identity',      question: 'What versions of you emerge repeatedly at different times? <em>Name the time and the version.</em>' },
      { label: 'VI · Strongest Shift',   question: 'What is the most noticeable timing-based identity or perception change in your life? <em>Name the specific transition.</em>' },
      { label: 'VII · The Rhythm Survey', question: 'For the next 7 days, what will you track? <em>Categories: emotional narrowing, repetition, protector activation, signal clarity, leakage, openness.</em>' },
    ],
    recordKind: 'structured',
    recordTitle: 'Timing Signal Map',
    recordLabels: [
      'High-Noise Temporal States',
      'Continuity-Amplifying Phases',
      'Transitional States',
      'Signal-Friendly Phases',
      'Strongest Temporal Shift',
      'Temporal Observation Pattern',
      '7-Day Observation Instruction',
    ],
    nextSessionId: 8,
    reflectionPromptKey: 'signal-7-reflection',
    recordPromptKey: 'signal-7-record',
    fallbackReflections: [
      'Different times produce different protectors. The version of you that wakes is not the version that lies down.',
      'Noisier periods are usually predictable in advance. Notice that the prediction itself is data.',
      'Continuity has rhythm. The pattern is not random; it cycles.',
      'Signal-friendly phases are rarely the productive ones. They are the quieter ones.',
      'Time-identity coupling is what makes most resolutions fail. The time stays the same.',
      'The strongest shift names itself. You already know it, even before this sentence finishes.',
      'A rhythm survey is reading what is already happening. Do not try to change the rhythm — just see it.',
    ],
  },

  /* =====================================================
     SESSION 8 — Hierarchy
     Phase II, Amplification Arc CLOSES. The final session.
     Perceptual discernment training: not all internal signals
     possess equal authority. The Levels (Reactive Momentum →
     Narrative Intelligence → Coherence-Based → Deep Structural)
     are perceptual mechanics, not spiritual ranks. Beats follow
     the canonical Session 8 stages authored by GPT.
     ===================================================== */
  8: {
    id: 8,
    title: 'Hierarchy',
    arc: 'Amplification',
    stageLabel: 'Session 8 · hierarchy',
    stageTitle: 'The closing session.<br>Today: <em>not all signals deserve equal authority.</em>',
    inputPlaceholder: 'Three moments where something inside felt true — but later showed different levels of clarity.',
    pacingNote: 'Intensity is not authority. <em>Loudest is rarely deepest.</em>',
    beats: [
      { label: 'I · Signal Recall',    question: 'Recall three moments where something inside you felt true — <em>but later revealed very different levels of clarity.</em>' },
      { label: 'II · Comparison',      question: 'Across those three, which felt urgent? <em>Which collapsed under emotional pressure? Which remained stable after time passed?</em>' },
      { label: 'III · Contamination',  question: 'Which of those signals was actually protector-driven? <em>Which certainty emerged from fear or required narrative reinforcement?</em>' },
      { label: 'IV · Depth',           question: 'Which perception remained coherent <em>without</em> urgency? Which signal widened rather than narrowed? Which clarity survived interruption?' },
      { label: 'V · The Four Levels',  question: 'Place each of your signals on the hierarchy. <em>Reactive Momentum / Narrative Intelligence / Coherence-Based / Deep Structural.</em> Be honest about where they sit.' },
      { label: 'VI · False Authority', question: 'What protector or urgency in your life <em>most often impersonates authority?</em> When do you confuse intensity with depth?' },
      { label: 'VII · Across the Arc', question: 'Look back across the eight sessions. <em>What is now louder in you than it was when you began?</em> What stability marker has emerged?' },
    ],
    recordKind: 'structured',
    recordTitle: 'Signal Authority Map',
    recordLabels: [
      'Reactive Momentum Signals',
      'Narrative Intelligence Signals',
      'Coherence-Based Signals',
      'Deep Structural Signals',
      'Most Common False Authority Pattern',
      'Strongest Stability Marker',
      '7-Day Observation Instruction',
    ],
    nextSessionId: null,
    reflectionPromptKey: 'signal-8-reflection',
    recordPromptKey: 'signal-8-record',
    fallbackReflections: [
      'Three signals are enough to compare. The variation across them is the data.',
      'Urgency and stability feel different from the inside. Most lives obey the louder one.',
      'Continuity often disguises itself as clarity. Protector-driven certainty is the most common kind.',
      'Depth is rarely dramatic. What survives interruption is closer to signal than what feels true in the moment.',
      'The Levels are perceptual mechanics, not spiritual rank. A useful signal at Level 2 can still be useful.',
      'The protector that imitates authority is familiar by now. Naming it on this list does not dissolve it.',
      'What has grown louder across the arc is the capacity that has begun to develop. Continue developing it.',
    ],
  },
};

// Active session is selected by ?session=N (defaults to 0).
function activeSessionId() {
  try {
    const id = parseInt(new URL(location).searchParams.get('session') || '0', 10);
    return SESSIONS[id] ? id : 0;
  } catch (e) { return 0; }
}
function sessionDef() { return SESSIONS[activeSessionId()]; }

/* ============================================================
   STATE
   Sessions accumulate across visits. We persist a small object.
   ============================================================ */
function loadState() {
  try {
    const raw = localStorage.getItem('signal.state');
    if (!raw) return defaultState();
    const parsed = JSON.parse(raw);
    return Object.assign(defaultState(), parsed);
  } catch (e) { return defaultState(); }
}
function defaultState() {
  return {
    firstSeen: null,
    lastSession: null,
    records: [],     // accumulated Resonance Records
    currentSession: null, // mid-session draft
  };
}
function saveState(state) {
  try { localStorage.setItem('signal.state', JSON.stringify(state)); } catch (e) {}
}

/* ============================================================
   RENDER
   The session is rendered into #stage. New exchanges are
   appended; the page scrolls slowly to follow.
   ============================================================ */
const $ = (sel) => document.querySelector(sel);
const $$ = (sel) => [...document.querySelectorAll(sel)];

const stage = $('#stage');
const inputZone = $('#input-zone');
const textarea = $('#input-text');
const submitBtn = $('#input-submit');
const thinking = $('#input-thinking');
const sessionId = $('#session-id');

let state = loadState();
let activeSession = ensureActiveSession();
let beatIndex = activeSession.exchanges.length; // resume where we left off
let isThinking = false;

function ensureActiveSession() {
  const def = sessionDef();
  if (state.currentSession && state.currentSession.id === def.id) {
    return state.currentSession;
  }
  const fresh = {
    id: def.id,
    title: def.title,
    exchanges: [],   // [{ beat, answer, reflection }]
    record: null,    // populated at end
    completed: false,
    startedAt: Date.now(),
  };
  state.currentSession = fresh;
  if (!state.firstSeen) state.firstSeen = Date.now();
  saveState(state);
  return fresh;
}

function renderExchange(ex, animated) {
  const beat = sessionDef().beats[ex.beat];
  const el = document.createElement('div');
  el.className = 's-exchange';
  if (!animated) el.style.animation = 'none';
  el.style.animationDelay = animated ? '200ms' : '0';

  el.innerHTML = `
    <div class="s-prompt">
      <span class="s-prompt-label">${beat.label}</span>
      ${beat.question}
    </div>
    <div class="s-answer">
      <span class="s-answer-label">You wrote</span>
      ${escapeHTML(ex.answer)}
    </div>
    ${ex.reflection ? `
      <div class="s-reflection">
        <span class="s-reflection-mark">·</span>${escapeHTML(ex.reflection)}
      </div>
    ` : ''}
  `;
  stage.appendChild(el);
}

function renderPendingQuestion(beat, animated) {
  const el = document.createElement('div');
  el.className = 's-exchange';
  el.id = 'pending-question';
  if (!animated) el.style.animation = 'none';
  el.innerHTML = `
    <div class="s-prompt">
      <span class="s-prompt-label">${beat.label}</span>
      ${beat.question}
    </div>
  `;
  stage.appendChild(el);
  if (animated) {
    setTimeout(() => {
      el.scrollIntoView({ behavior: 'smooth', block: 'center' });
      textarea.focus();
    }, 800);
  } else {
    textarea.focus();
  }
}

function escapeHTML(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

/* ============================================================
   INTERACTION
   ============================================================ */
async function handleSubmit() {
  if (isThinking) return;
  const answer = textarea.value.trim();
  if (answer.length < 6) return; // require something

  isThinking = true;
  submitBtn.disabled = true;
  thinking.style.display = 'inline-flex';
  textarea.disabled = true;

  // Convert the pending-question into a fully rendered exchange
  const pending = document.getElementById('pending-question');
  if (pending) pending.remove();

  // Build exchange (no reflection yet)
  const exchange = { beat: beatIndex, answer: answer, reflection: null };
  activeSession.exchanges.push(exchange);
  saveState(state);

  renderExchange(exchange, true);
  textarea.value = '';
  autosize();

  // Slow pause — let the answer sit on screen
  await sleep(900);

  // Get live reflection from Claude (with graceful fallback)
  let reflection = '';
  try {
    reflection = await getReflection(beatIndex, answer);
  } catch (e) {
    reflection = fallbackReflection(beatIndex);
  }
  exchange.reflection = reflection;
  saveState(state);

  // Update the just-rendered exchange to include the reflection
  const lastEx = stage.querySelector('.s-exchange:last-child');
  if (lastEx) {
    const refEl = document.createElement('div');
    refEl.className = 's-reflection';
    refEl.style.opacity = '0';
    refEl.innerHTML = `<span class="s-reflection-mark">·</span>${escapeHTML(reflection)}`;
    lastEx.appendChild(refEl);
    requestAnimationFrame(() => {
      refEl.style.transition = 'opacity 1400ms ease-out';
      refEl.style.opacity = '1';
    });
  }

  await sleep(1800);

  // Advance to next beat
  beatIndex += 1;
  isThinking = false;
  thinking.style.display = 'none';
  // Atmosphere re-tunes as the beat depth changes (early → mid → late)
  applyAtmosphere(sessionDef(), beatIndex);

  if (beatIndex < sessionDef().beats.length) {
    renderPendingQuestion(sessionDef().beats[beatIndex], true);
    textarea.disabled = false;
    submitBtn.disabled = false;
    textarea.focus();
  } else {
    // Session complete — generate Resonance Record
    await completeSession();
  }
}

async function getReflection(beatIdx, answer) {
  if (!window.claude || !window.claude.complete) {
    return fallbackReflection(beatIdx);
  }
  const def = sessionDef();
  const beatLabel = def.beats[beatIdx].label;
  const userPrompt = `BEAT: ${beatLabel}
QUESTION ASKED: ${stripHTML(def.beats[beatIdx].question)}
READER'S ANSWER:
${answer}

Now produce your reflection.`;

  const result = await window.claude.complete({
    messages: [
      { role: 'user', content: composeWithKnowledge(getReflectionSystem(), getReflectionKnowledge()) + '\n\n---\n\n' + userPrompt },
    ],
  });
  let text = String(result || '').trim();
  // Strip any quote marks the model might wrap with
  text = text.replace(/^["']|["']$/g, '');
  // Cap aggressively — reflections must stay short
  if (text.length > 240) text = text.slice(0, 240).replace(/\s+\S*$/, '') + '…';
  // Reject anything containing forbidden words — graceful fallback
  if (/\b(journey|mindset|resonance|vibration|holistic|mindful)\b/i.test(text)
    || /\b(great|beautiful|powerful|amazing|wonderful)\b/i.test(text)
    || /\b(thank you for sharing)\b/i.test(text)) {
    return fallbackReflection(beatIdx);
  }
  if (!text || text.length < 6) return fallbackReflection(beatIdx);
  return text;
}

function fallbackReflection(beatIdx) {
  // Per-session hand-written fallbacks — used when the AI is unavailable
  // or produces something that violates the prompt's hard rules.
  const fallbacks = sessionDef().fallbackReflections || [];
  return fallbacks[beatIdx] || fallbacks[0] || 'Notice what you just wrote. The next question follows from it.';
}

function stripHTML(s) { return String(s).replace(/<[^>]+>/g, ''); }

async function completeSession() {
  // Show the slow record-generation interlude
  inputZone.style.display = 'none';

  const interlude = document.createElement('div');
  interlude.className = 's-sit-with';
  interlude.style.opacity = '0';
  interlude.innerHTML = 'A moment. The field is composing the record of what you surfaced.';
  stage.appendChild(interlude);
  requestAnimationFrame(() => {
    interlude.style.transition = 'opacity 1800ms ease-out';
    interlude.style.opacity = '1';
  });

  await sleep(2400);

  let record;
  try {
    record = await generateRecord();
  } catch (e) {
    record = fallbackRecord();
  }

  // Save the completed record to permanent state
  activeSession.record = record;
  activeSession.completed = true;
  activeSession.completedAt = Date.now();
  state.records.push({
    sessionId: activeSession.id,
    sessionTitle: activeSession.title,
    record: record,
    when: activeSession.completedAt,
  });
  state.lastSession = { idx: activeSession.id + 1, completedAt: activeSession.completedAt };
  state.currentSession = null;
  saveState(state);

  // Render the Resonance Record
  await sleep(400);
  interlude.style.transition = 'opacity 800ms ease-out';
  interlude.style.opacity = '0';
  await sleep(900);
  interlude.remove();

  const recordEl = document.createElement('div');
  recordEl.className = 's-record';
  recordEl.style.opacity = '0';
  const def = sessionDef();
  const recordLabel = def.recordTitle
    ? def.recordTitle + ' · Session ' + String(def.id).padStart(2, '0')
    : `Resonance Record${def.id === 0 ? '' : ' ' + def.id} · Session ${String(def.id).padStart(2, '0')}`;
  const nextHref = def.nextSessionId != null && SESSIONS[def.nextSessionId]
    ? `session.html?session=${def.nextSessionId}`
    : 'field.html';
  const nextLabel = def.nextSessionId != null && SESSIONS[def.nextSessionId]
    ? `Begin Session ${def.nextSessionId} — <em>${SESSIONS[def.nextSessionId].title}</em> →`
    : 'View the Field →';
  recordEl.innerHTML = `
    <div class="s-record-label">${escapeHTML(recordLabel)}</div>
    <div class="s-record-title"><em>${escapeHTML(activeSession.title)}</em></div>
    <div class="s-record-body">
      ${renderRecordBody(record)}
    </div>
    <div class="s-record-actions">
      <a href="field.html">View the Field →</a>
      <a href="${nextHref}" class="next">${nextLabel}</a>
    </div>
  `;
  stage.appendChild(recordEl);
  requestAnimationFrame(() => {
    recordEl.style.transition = 'opacity 2200ms ease-out';
    recordEl.style.opacity = '1';
    setTimeout(() => recordEl.scrollIntoView({ behavior: 'smooth', block: 'center' }), 200);
  });
}

async function generateRecord() {
  if (!window.claude || !window.claude.complete) return fallbackRecord();

  const def = sessionDef();
  const transcript = activeSession.exchanges.map((ex, i) => {
    const beat = def.beats[ex.beat];
    return `${beat.label}\nQ: ${stripHTML(beat.question)}\nA: ${ex.answer}`;
  }).join('\n\n');

  const userPrompt = `Here is the full Session ${def.id} transcript. Produce the Resonance Record per the format above.

TRANSCRIPT:
${transcript}`;

  const result = await window.claude.complete({
    messages: [
      { role: 'user', content: composeWithKnowledge(getRecordSystem(), getRecordKnowledge()) + '\n\n---\n\n' + userPrompt },
    ],
  });
  const text = String(result || '').trim();
  if (!text || text.length < 30) return fallbackRecord();
  return text;
}

function fallbackRecord() {
  const id = activeSessionId();
  if (id === 0) {
    return `The situation: A real friction the reader is currently carrying.

The trade: Something concrete is being given up to keep something else intact.

The split: The two cannot both be held without contradiction.

The split is the place where development becomes possible. Notice it without trying to fix it.`;
  }
  if (id === 1) {
    return `Detected Trade: The distortion is purchasing something the reader is not yet willing to lose.

Avoided Cost: A risk or responsibility that would have to be faced if the trade ended.

Protective Narrative: The justification structure the reader has been using to keep both sides intact.

Actual Price Being Paid: Time, energy, decisiveness, or a relationship has already been spent.

Witnessing Instruction: For the next 48 hours, do not try to end the pattern. Watch every moment the trade is being re-made.`;
  }
  if (id === 2) {
    return `Primary Protector: The recurring continuity-preserving self that activates during capture.

Preserved Function: What this protector\u2019s presence keeps intact.

Prevented Reality: What this protector\u2019s presence keeps from being faced.

Activation Trigger: The conditions under which the protector reliably appears.

Earliest Activation Signal: The first concrete sign — posture, narrative, perception — that the protector is taking control.

72-Hour Observation Instruction: For the next 72 hours, do not suppress the protector. Only observe every moment it begins taking control.`;
  }
  if (id === 3) {
    return `Detected Pattern: A specific recent capture sequence the reader has reconstructed.

Trigger: What initiated the sequence.

Earliest Charge: The first detectable bodily or emotional shift.

Interpretation: The meaning the mind assigned before the lock.

Activated Protector: The identity structure that took control.

Continuity Lock Point: Where alternatives disappeared and the outcome started to feel inevitable.

Possible Interruption Window: The earliest realistic point at which the sequence could have been interrupted.

Lower-Leakage Alternative: A coherence-preserving action available inside that window.

72-Hour Observation Instruction: For the next 72 hours, do not eliminate patterns. Only detect continuity forming before lock stabilizes.`;
  }
  if (id === 4) {
    return `Primary Noise Pattern: The most common distortion source in the reader's current perception.

Signal State Detected: A description of the lower-noise perceptual state the reader contacted.

Narrative Re-entry Pattern: How the mind reconstructs continuity after the space opens.

Widening Mechanism: What weakened narrowing — body, environment, silence, breath.

Stable Signal Observation: What remained coherent without emotional urgency.

Environmental Sensitivity Observation: Places, people, and situations affecting signal stability.

72-Hour Observation Instruction: Across the next 72 hours, notice environments and presences that make perception either quieter or noisier.`;
  }
  if (id === 5) {
    return `Decision Pressure: A live decision, action, or non-action currently generating pressure for the reader.

Continuity Influence: What current structure the decision would preserve if continuity won.

Highest Leakage Option: The path that produces the most internal division and narrative maintenance.

Lowest Leakage Option: The path that requires the least identity protection and reduces fragmentation.

Identity Resistance: The protector resisting the coherent movement.

Stabilized Signal Observation: What remained coherent after urgency settled.

72-Hour Observation Instruction: For the next 72 hours, observe which actions increase fragmentation and which reduce it.`;
  }
  if (id === 6) {
    return `High-Noise Environments: The places that most reliably increase fragmentation, urgency, and protector activation.

Continuity-Amplifying Environments: Places that reinforce the reader's familiar identity and protector structures.

Transitional Environments: Mixed or unstable environments that produce variable states.

Signal-Friendly Environments: Places that stabilize coherence and widen perception without force.

Strongest Environmental Shift: The most noticeable identity or perception change across all environments inhabited.

Environmental Observation Pattern: The recurring place-based continuity structure visible in the reader's life.

7-Day Observation Instruction: For the next 7 days, observe how different environments alter continuity, urgency, perception, and coherence.`;
  }
  if (id === 7) {
    return `High-Noise Temporal States: Periods that most reliably increase fragmentation, urgency, and protector activation.

Continuity-Amplifying Phases: Times that strengthen protector structures and intensify familiar patterns.

Transitional States: Mixed or unstable temporal phases.

Signal-Friendly Phases: Periods that stabilize coherence and widen perception without force.

Strongest Temporal Shift: The most noticeable timing-based identity or perception change.

Temporal Observation Pattern: A recurring time-based continuity structure visible in the reader's life.

7-Day Observation Instruction: For the next 7 days, observe how time alters continuity, urgency, protector intensity, and coherence.`;
  }
  if (id === 8) {
    return `Reactive Momentum Signals: Urgency-driven, fear-driven, or emotional-acceleration signals the reader noticed across the arc.

Narrative Intelligence Signals: Reasoned, interpretive, conceptual signals \u2014 useful but often continuity-shaped.

Coherence-Based Signals: Low-fragmentation signals that widened perception and required less identity protection.

Deep Structural Signals: The rare perceptions that persisted across place, time, emotion, and identity.

Most Common False Authority Pattern: The protector or urgency that most often impersonates authority for this reader.

Strongest Stability Marker: What has persisted across conditions \u2014 the capacity that has developed across the arc.

7-Day Observation Instruction: For the next 7 days, observe which signals weaken and which remain stable as urgency decreases.`;
  }
  // Generic fallback for any future session
  return `The structure: What the session surfaced about the reader's current architecture.

The instruction: A small observational task to hold until the next session.

Notice the structure without trying to fix it. The fixing comes later.`;
}

function renderRecordBody(text) {
  const def = sessionDef();
  const kind = def.recordKind || 'paragraphs';
  if (kind === 'structured') {
    // Per-session labels (def.recordLabels) win; legacy default is the
    // five-field Resonance Record 1 schema.
    const labels = def.recordLabels || [
      'Detected Trade', 'Avoided Cost', 'Protective Narrative',
      'Actual Price Being Paid', 'Witnessing Instruction',
    ];
    const found = {};
    // Find each label and capture everything until the next label.
    for (let i = 0; i < labels.length; i++) {
      const here = labels[i];
      const re = new RegExp('(?:^|\\n)\\s*' + here.replace(/ /g, '\\s+') + '\\s*:\\s*([\\s\\S]*?)(?=\\n\\s*(?:' + labels.filter((_, j) => j !== i).map(l => l.replace(/ /g, '\\s+')).join('|') + ')\\s*:|$)', 'i');
      const m = text.match(re);
      if (m && m[1]) found[here] = m[1].trim();
    }
    if (Object.keys(found).length === 0) {
      // Couldn't parse — fall back to paragraphs
      return paragraphsRender(text);
    }
    // The LAST present label is always rendered as the closing
    // observation block — italic, ember-bordered. By convention, the
    // witnessing / observation instruction is always last.
    const presentLabels = labels.filter(l => found[l]);
    const lastLabel = presentLabels[presentLabels.length - 1];
    return presentLabels.map(l => {
      const isLast = l === lastLabel;
      const cls = isLast ? 'srf-witness' : '';
      return `
        <div class="srf-block ${cls}">
          <div class="srf-label">${escapeHTML(l)}</div>
          <div class="srf-value">${isLast ? '<em>' + escapeHTML(found[l]) + '</em>' : escapeHTML(found[l])}</div>
        </div>
      `;
    }).join('');
  }
  return paragraphsRender(text);
}

function paragraphsRender(text) {
  const blocks = text.split(/\n\s*\n/).map(b => b.trim()).filter(Boolean);
  return blocks.map((b, i) => {
    const isLast = i === blocks.length - 1;
    return isLast ? `<p><em>${escapeHTML(b)}</em></p>` : `<p>${escapeHTML(b)}</p>`;
  }).join('');
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

/* ============================================================
   AUTOSIZE textarea
   ============================================================ */
function autosize() {
  textarea.style.height = 'auto';
  textarea.style.height = Math.min(textarea.scrollHeight, 240) + 'px';
}

/* ============================================================
   BOOT
   ============================================================ */
/* ============================================================
   ATMOSPHERIC FIELD STATES
   ============================================================
   Subtle data-attribute on <body> per session arc + beat depth.
   CSS in signal.css responds with near-subconscious environmental
   shifts. The state changes automatically as the reader moves
   through the session.
   ============================================================ */
function applyAtmosphere(def, beatIdx) {
  document.body.setAttribute('data-arc', def.arc || 'Correction');
  document.body.setAttribute('data-session-id', String(def.id));
  const total = (def.beats || []).length || 1;
  let stage = 'mid';
  if (beatIdx < Math.ceil(total / 3)) stage = 'early';
  else if (beatIdx >= total - Math.floor(total / 3)) stage = 'late';
  document.body.setAttribute('data-beat-stage', stage);
}

/* ============================================================
   MEMORY THREAD
   ============================================================
   At the top of a session (other than Session 0), surface the
   closing line of the reader's most recent Resonance Record.
   Continuity, not summary. The reader feels: "the field remembers
   the work I did last session" — never "this AI knows me".

   The thread shows ONLY for fresh-start sessions, never mid-flow
   or on a re-shown completed session.
   ============================================================ */
function renderMemoryThread(def) {
  if (def.id === 0) return;                                         // first session — no prior
  if (!state.records || state.records.length === 0) return;
  if (activeSession.exchanges && activeSession.exchanges.length > 0) return;
  if (activeSession.completed) return;

  const lastRecord = state.records[state.records.length - 1];
  if (!lastRecord || !lastRecord.record) return;

  // Extract the closing line:
  //   • structured Resonance Record 1 → "Witnessing Instruction"
  //   • paragraphs record → last paragraph (the italic closing line)
  let closing = '';
  const text = String(lastRecord.record).trim();
  const witnessMatch = text.match(/Witnessing Instruction\s*:\s*([\s\S]+?)$/i);
  if (witnessMatch) {
    closing = witnessMatch[1].trim();
  } else {
    const paras = text.split(/\n\s*\n/).map(p => p.trim()).filter(Boolean);
    closing = paras[paras.length - 1] || '';
  }
  if (!closing) return;
  if (closing.length > 240) closing = closing.slice(0, 240).replace(/\s+\S*$/, '') + '…';

  const refLabel = `Session ${String(lastRecord.sessionId).padStart(2, '0')} · ${lastRecord.sessionTitle || ''}`;
  const thread = document.createElement('div');
  thread.className = 's-memory-thread';
  thread.innerHTML = `
    <div class="s-memory-label">The field remembers</div>
    <div class="s-memory-body">
      ${escapeHTML(closing)}
      <span class="s-memory-ref">— ${escapeHTML(refLabel)}</span>
    </div>
  `;
  const title = stage.querySelector('.s-stage-title');
  if (title && title.nextSibling) stage.insertBefore(thread, title.nextSibling);
  else stage.appendChild(thread);
}

function boot() {
  const def = sessionDef();
  // Atmosphere — set the room before anything else paints
  applyAtmosphere(def, beatIndex);
  // Update session id label
  if (sessionId) sessionId.innerHTML = `Session <em>${String(def.id).padStart(2, '0')}</em> · ${escapeHTML(def.title)}`;
  // Update stage eyebrow/title from session config
  const eb = document.querySelector('.s-stage-eyebrow');
  if (eb) eb.textContent = def.stageLabel || eb.textContent;
  const st = document.querySelector('.s-stage-title');
  if (st) st.innerHTML = def.stageTitle || st.innerHTML;
  if (textarea && def.inputPlaceholder) textarea.placeholder = def.inputPlaceholder;
  const pacing = document.querySelector('.s-pacing');
  if (pacing && def.pacingNote) pacing.innerHTML = def.pacingNote;
  document.title = `Session ${def.id} · ${def.title} — The Signal`;

  // Memory thread — surface continuity from the previous session, if any
  renderMemoryThread(def);

  // Render any existing exchanges (returning reader mid-session)
  for (const ex of activeSession.exchanges) {
    renderExchange(ex, false);
  }
  // Show next beat or complete session
  if (activeSession.completed) {
    // Re-show the existing record
    if (activeSession.record) {
      const recordLabel = def.recordTitle
        ? def.recordTitle + ' · Session ' + String(def.id).padStart(2, '0')
        : `Resonance Record${def.id === 0 ? '' : ' ' + def.id} · Session ${String(def.id).padStart(2, '0')}`;
      const nextHref = def.nextSessionId != null && SESSIONS[def.nextSessionId]
        ? `session.html?session=${def.nextSessionId}`
        : 'field.html';
      const nextLabel = def.nextSessionId != null && SESSIONS[def.nextSessionId]
        ? `Begin Session ${def.nextSessionId} — ${SESSIONS[def.nextSessionId].title} →`
        : 'Begin a new session';
      const recordEl = document.createElement('div');
      recordEl.className = 's-record';
      recordEl.innerHTML = `
        <div class="s-record-label">${escapeHTML(recordLabel)}</div>
        <div class="s-record-title"><em>${escapeHTML(activeSession.title)}</em></div>
        <div class="s-record-body">
          ${renderRecordBody(activeSession.record)}
        </div>
        <div class="s-record-actions">
          <a href="field.html">View the Field →</a>
          <a href="${nextHref}" class="next">${nextLabel}</a>
        </div>
      `;
      stage.appendChild(recordEl);
      inputZone.style.display = 'none';
    }
  } else if (beatIndex < def.beats.length) {
    renderPendingQuestion(def.beats[beatIndex], beatIndex === 0);
  }

  // Wire input
  textarea.addEventListener('input', autosize);
  textarea.addEventListener('keydown', (e) => {
    if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
      e.preventDefault();
      handleSubmit();
    }
  });
  submitBtn.addEventListener('click', handleSubmit);
}

document.addEventListener('DOMContentLoaded', boot);
