/* =============================================================
   videos-admin.js — the video editor
   =============================================================
   - Loads current videos from assets/data/videos.json (or
     localStorage drafts if newer).
   - All edits update localStorage 'studio.videos' immediately.
   - "Publish & download" exports a fresh videos.json that you
     replace in the repo.
   - The public watch page reads from localStorage first (so you
     can preview), then assets/data/videos.json.

   Adding a video by URL:
   - Paste any YouTube URL.
   - We extract the video ID and detect whether it's a Short.
   - Title + duration are fetched via YouTube's public oEmbed
     endpoint (no API key needed). If that fails (CORS/etc.),
     we still create the entry with the ID + thumbnail so you
     can fill the title manually.

   Instagram / LinkedIn: paste the URL, we detect the platform,
   the rest you fill manually (their oEmbed needs an access token).
   ============================================================= */

const TOPICS = [
  { id: 'siv',       label: 'The SIV Method'      },
  { id: 'ai',        label: 'AI for Business'     },
  { id: 'execution', label: 'Execution'           },
  { id: 'signal',    label: 'The Signal'          },
  { id: 'general',   label: 'Notes & reflections' },
];

const PLATFORM_LABELS = {
  'youtube':        'YouTube',
  'youtube-shorts': 'YouTube Shorts',
  'instagram':      'Instagram',
  'linkedin':       'LinkedIn',
  'x':              'X',
};

const STATE_KEY = 'studio.videos';

let editorState = {
  videos: [],
  expandedId: null,
  dirty: false,
};

/* ------------------------------------------------------------
   LOAD / SAVE
   ------------------------------------------------------------ */
async function loadState() {
  // Drafts first
  try {
    const draft = localStorage.getItem(STATE_KEY);
    if (draft) {
      const parsed = JSON.parse(draft);
      if (Array.isArray(parsed?.videos)) {
        editorState.videos = parsed.videos;
        editorState.dirty = true; // there are unpublished local edits
        return;
      }
    }
  } catch (e) {}
  // Fall back to published file
  try {
    const res = await fetch('../assets/data/videos.json', { cache: 'no-cache' });
    if (res.ok) {
      const data = await res.json();
      editorState.videos = data.videos || [];
    }
  } catch (e) {
    editorState.videos = [];
  }
}

function saveDraft() {
  const payload = {
    _comment: 'Studio draft — overrides published videos.json until you publish.',
    updated_at: new Date().toISOString().slice(0, 10),
    videos: editorState.videos,
  };
  localStorage.setItem(STATE_KEY, JSON.stringify(payload, null, 2));
  editorState.dirty = true;
  updateStatus();
}

function updateStatus() {
  const el = document.getElementById('editor-status');
  if (!el) return;
  if (editorState.dirty) {
    el.innerHTML = `<span class="dirty">● Unpublished changes on this device</span>`;
  } else {
    el.innerHTML = `<span class="saved">All changes saved on this device</span>`;
  }
}

function downloadJSON() {
  const payload = {
    _comment: 'Source of truth for videos. Generated by the studio editor.',
    updated_at: new Date().toISOString().slice(0, 10),
    videos: editorState.videos,
  };
  const json = JSON.stringify(payload, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'videos.json';
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 500);
}

/* ------------------------------------------------------------
   YOUTUBE URL PARSING + METADATA FETCH
   ------------------------------------------------------------ */
function parseVideoUrl(input) {
  if (!input) return null;
  const url = input.trim();
  // YouTube long-form
  let m = url.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/)([\w-]{6,})/);
  if (m) return { platform: 'youtube', id: m[1] };
  // YouTube Shorts
  m = url.match(/youtube\.com\/shorts\/([\w-]{6,})/);
  if (m) return { platform: 'youtube-shorts', id: m[1] };
  // YouTube embed
  m = url.match(/youtube\.com\/embed\/([\w-]{6,})/);
  if (m) return { platform: 'youtube', id: m[1] };
  // Instagram reel/p
  m = url.match(/instagram\.com\/(?:reel|p|reels)\/([\w-]+)/);
  if (m) return { platform: 'instagram', id: m[1] };
  // LinkedIn post
  m = url.match(/linkedin\.com\/(?:posts|feed\/update)\/([\w-]+)/);
  if (m) return { platform: 'linkedin', id: m[1] };
  // X
  m = url.match(/(?:twitter\.com|x\.com)\/[^/]+\/status\/(\d+)/);
  if (m) return { platform: 'x', id: m[1] };
  return null;
}

async function fetchYouTubeMeta(videoId, isShort) {
  // YouTube oEmbed is open (no API key) and CORS-permissive.
  // It returns: title, author_name, thumbnail_url, html
  const url = `https://www.youtube.com/oembed?url=${encodeURIComponent(
    isShort
      ? `https://www.youtube.com/shorts/${videoId}`
      : `https://www.youtube.com/watch?v=${videoId}`
  )}&format=json`;
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    return await res.json();
  } catch (e) {
    return null;
  }
}

/* ------------------------------------------------------------
   ADD / EDIT / DELETE / REORDER
   ------------------------------------------------------------ */
async function addVideoByUrl(url) {
  const parsed = parseVideoUrl(url);
  if (!parsed) {
    return { error: 'Couldn\u2019t recognise that URL. Try a YouTube / Instagram / LinkedIn / X link.' };
  }
  // Already exists?
  if (editorState.videos.some(v => v.platform_id === parsed.id)) {
    return { error: 'That video is already in the list.' };
  }

  // Build entry
  const isShort = parsed.platform === 'youtube-shorts';
  const newId = `${parsed.platform === 'youtube-shorts' ? 'yt' : parsed.platform.slice(0, 2)}-${parsed.id}`;
  const entry = {
    id: newId,
    title: 'Untitled video',
    blurb: '',
    platform: parsed.platform,
    platform_id: parsed.id,
    duration: '—',
    date: new Date().toISOString().slice(0, 10),
    topic: 'general',
    hashtags: [],
  };

  // Auto-fetch title from YouTube oEmbed
  if (parsed.platform === 'youtube' || parsed.platform === 'youtube-shorts') {
    const meta = await fetchYouTubeMeta(parsed.id, isShort);
    if (meta?.title) entry.title = meta.title;
  }

  // Insert at top
  editorState.videos.unshift(entry);
  saveDraft();
  editorState.expandedId = newId;
  render();
  // Smooth scroll to it
  setTimeout(() => {
    document.querySelector(`[data-vid="${newId}"]`)?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  }, 60);
  return { ok: true, entry };
}

function updateVideo(id, patch) {
  const v = editorState.videos.find(v => v.id === id);
  if (!v) return;
  // Featured exclusivity
  if (patch.featured) {
    editorState.videos.forEach(o => { if (o.id !== id) o.featured = false; });
  }
  Object.assign(v, patch);
  saveDraft();
}

function deleteVideo(id) {
  editorState.videos = editorState.videos.filter(v => v.id !== id);
  saveDraft();
  render();
}

function moveVideo(id, dir) {
  const idx = editorState.videos.findIndex(v => v.id === id);
  if (idx === -1) return;
  const target = idx + dir;
  if (target < 0 || target >= editorState.videos.length) return;
  const [item] = editorState.videos.splice(idx, 1);
  editorState.videos.splice(target, 0, item);
  saveDraft();
  render();
}

function setFeatured(id) {
  editorState.videos.forEach(v => { v.featured = v.id === id; });
  saveDraft();
  render();
}

/* ------------------------------------------------------------
   RENDER
   ------------------------------------------------------------ */
function render() {
  const host = document.getElementById('video-list');
  const count = document.getElementById('tb-count');
  if (!host) return;
  count.textContent = `${editorState.videos.length} video${editorState.videos.length === 1 ? '' : 's'}`;

  if (!editorState.videos.length) {
    host.innerHTML = `
      <div class="vl-empty">
        <p>No videos yet. <em>Paste a URL above to add one.</em></p>
      </div>
    `;
    return;
  }

  host.innerHTML = editorState.videos.map(renderVideoItem).join('');
  wireVideoItems();
  updateStatus();
}

function renderVideoItem(v) {
  const platform = PLATFORM_LABELS[v.platform] || v.platform;
  const isYt = v.platform === 'youtube' || v.platform === 'youtube-shorts';
  const thumb = isYt
    ? `<img src="https://i.ytimg.com/vi/${v.platform_id}/hqdefault.jpg" alt="thumb" onerror="this.style.display='none'">`
    : `<div class="placeholder">${escapeHTML(platform)}</div>`;

  const topicLabel = TOPICS.find(t => t.id === v.topic)?.label || v.topic;

  const main = `
    <div class="vli-handle" title="drag to reorder">⋮⋮</div>
    <div class="vli-thumb">
      ${thumb}
      <span class="platform-badge">${escapeHTML(platform.split(' ')[0])}</span>
    </div>
    <div class="vli-body">
      <div class="vli-title">${escapeHTML(v.title || 'Untitled')}</div>
      <div class="vli-meta">
        <span class="topic">${escapeHTML(topicLabel)}</span>
        <span class="dot">·</span>
        <span>${escapeHTML(v.date || '—')}</span>
        <span class="dot">·</span>
        <span>${escapeHTML(v.duration || '—')}</span>
        <span class="dot">·</span>
        <span>${escapeHTML(platform)}</span>
        ${v.featured ? '<span class="dot">·</span><span class="featured-tag">★ featured</span>' : ''}
      </div>
    </div>
    <div class="vli-actions">
      <button class="vli-action" data-act="up" data-id="${v.id}" title="Move up">↑</button>
      <button class="vli-action" data-act="down" data-id="${v.id}" title="Move down">↓</button>
      <button class="vli-action" data-act="toggle" data-id="${v.id}">${editorState.expandedId === v.id ? 'Close' : 'Edit'}</button>
      <button class="vli-action danger" data-act="delete" data-id="${v.id}">Delete</button>
    </div>
  `;

  if (editorState.expandedId !== v.id) {
    return `<div class="vli ${v.featured ? 'featured' : ''}" data-vid="${v.id}">${main}</div>`;
  }

  // Edit panel
  return `
    <div class="vli ${v.featured ? 'featured' : ''} expanded" data-vid="${v.id}">
      ${main}
      <div class="vli-edit">
        <label class="full">
          Title
          <input type="text" data-field="title" data-id="${v.id}" value="${escapeAttr(v.title || '')}">
        </label>
        <label class="full">
          Blurb
          <textarea data-field="blurb" data-id="${v.id}">${escapeHTML(v.blurb || '')}</textarea>
          <span class="help">1–2 sentences shown beneath the title.</span>
        </label>
        <label>
          Topic
          <select data-field="topic" data-id="${v.id}">
            ${TOPICS.map(t => `<option value="${t.id}" ${t.id === v.topic ? 'selected' : ''}>${t.label}</option>`).join('')}
          </select>
        </label>
        <label>
          Platform
          <select data-field="platform" data-id="${v.id}">
            ${Object.entries(PLATFORM_LABELS).map(([k, l]) => `<option value="${k}" ${k === v.platform ? 'selected' : ''}>${l}</option>`).join('')}
          </select>
        </label>
        <label>
          Video ID
          <input type="text" data-field="platform_id" data-id="${v.id}" value="${escapeAttr(v.platform_id || '')}">
          <span class="help">YouTube ID (e.g. <code>I0FDttzhxWI</code>) or the URL slug for other platforms.</span>
        </label>
        <label>
          Duration
          <input type="text" data-field="duration" data-id="${v.id}" value="${escapeAttr(v.duration || '')}" placeholder="0:58">
        </label>
        <label>
          Publish date
          <input type="date" data-field="date" data-id="${v.id}" value="${escapeAttr(v.date || '')}">
        </label>
        <label class="full">
          Hashtags <span class="help" style="margin-top:0">comma-separated, no &#35;</span>
          <input type="text" data-field="hashtags" data-id="${v.id}" value="${escapeAttr((v.hashtags || []).join(', '))}">
        </label>
        <div class="checkbox-row">
          <input type="checkbox" data-field="featured" data-id="${v.id}" id="feat-${v.id}" ${v.featured ? 'checked' : ''}>
          <label for="feat-${v.id}">Featured (shown large at the top of the page — only one at a time)</label>
        </div>
        <div class="vli-edit-actions">
          <button class="tb-btn ghost" type="button" data-act="close" data-id="${v.id}">Done editing</button>
        </div>
      </div>
    </div>
  `;
}

function wireVideoItems() {
  // Action buttons
  document.querySelectorAll('.vli-action').forEach(b => {
    b.addEventListener('click', e => {
      const id = e.currentTarget.dataset.id;
      const act = e.currentTarget.dataset.act;
      if (act === 'up') moveVideo(id, -1);
      else if (act === 'down') moveVideo(id, 1);
      else if (act === 'toggle') {
        editorState.expandedId = editorState.expandedId === id ? null : id;
        render();
      } else if (act === 'delete') {
        if (confirm('Delete this video?')) deleteVideo(id);
      }
    });
  });
  // Close edit panel
  document.querySelectorAll('[data-act="close"]').forEach(b => {
    b.addEventListener('click', e => {
      editorState.expandedId = null;
      render();
    });
  });

  // Field changes
  document.querySelectorAll('[data-field]').forEach(input => {
    const evt = input.tagName === 'SELECT' || input.type === 'checkbox' || input.type === 'date' ? 'change' : 'input';
    input.addEventListener(evt, e => {
      const id = e.currentTarget.dataset.id;
      const field = e.currentTarget.dataset.field;
      let value;
      if (e.currentTarget.type === 'checkbox') value = e.currentTarget.checked;
      else value = e.currentTarget.value;
      // Special: hashtags → array
      if (field === 'hashtags') {
        value = value.split(',').map(s => s.trim().replace(/^#/, '')).filter(Boolean);
      }
      updateVideo(id, { [field]: value });
      // Light re-render to update meta line and featured exclusivity
      if (['title', 'topic', 'date', 'duration', 'platform', 'featured'].includes(field)) {
        // Update the title in the meta strip without full re-render
        if (field === 'title') {
          const el = document.querySelector(`[data-vid="${id}"] .vli-title`);
          if (el) el.textContent = value;
        }
        if (field === 'featured') render();
      }
    });
  });
}

/* ------------------------------------------------------------
   QUICK ADD
   ------------------------------------------------------------ */
function wireQuickAdd() {
  const url = document.getElementById('qa-url');
  const btn = document.getElementById('qa-btn');
  const err = document.getElementById('qa-error');
  const hint = document.getElementById('qa-hint');
  const submit = async () => {
    err.style.display = 'none';
    btn.disabled = true;
    const orig = btn.innerHTML;
    btn.textContent = 'Fetching…';
    const result = await addVideoByUrl(url.value);
    btn.disabled = false;
    btn.innerHTML = orig;
    if (result.error) {
      err.textContent = result.error;
      err.style.display = '';
      return;
    }
    url.value = '';
    showToast('Added — fill in the details below');
  };
  btn.addEventListener('click', submit);
  url.addEventListener('keydown', e => {
    if (e.key === 'Enter') { e.preventDefault(); submit(); }
  });
}

/* ------------------------------------------------------------
   TOOLBAR ACTIONS
   ------------------------------------------------------------ */
function wireToolbar() {
  document.getElementById('btn-publish')?.addEventListener('click', () => {
    downloadJSON();
    // Open modal explaining deploy steps
    document.getElementById('publish-overlay').style.display = 'flex';
    // We treat publish as "downloaded" — leave dirty flag until user replaces file
  });
  document.getElementById('publish-close')?.addEventListener('click', () => {
    document.getElementById('publish-overlay').style.display = 'none';
  });
  document.getElementById('btn-reset')?.addEventListener('click', async () => {
    if (!confirm('Revert all unpublished changes on this device? Your local edits will be lost.')) return;
    localStorage.removeItem(STATE_KEY);
    editorState.dirty = false;
    await loadState();
    render();
    showToast('Reverted to published state');
  });
  document.getElementById('btn-import')?.addEventListener('click', () => {
    document.getElementById('import-file').click();
  });
  document.getElementById('import-file')?.addEventListener('change', async (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    try {
      const text = await file.text();
      const data = JSON.parse(text);
      if (!Array.isArray(data.videos)) throw new Error('No videos array');
      editorState.videos = data.videos;
      saveDraft();
      render();
      showToast('Imported');
    } catch (err) {
      alert('Couldn\u2019t read that file. Make sure it\u2019s a videos.json with a "videos" array.');
    }
    e.target.value = ''; // allow re-import same file
  });
}

/* ------------------------------------------------------------
   UTILS
   ------------------------------------------------------------ */
function escapeHTML(s) {
  return String(s || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
function escapeAttr(s) {
  return String(s || '')
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function showToast(msg) {
  const t = document.getElementById('toast');
  if (!t) return;
  t.textContent = msg;
  t.classList.add('show');
  clearTimeout(showToast._t);
  showToast._t = setTimeout(() => t.classList.remove('show'), 2200);
}

/* ------------------------------------------------------------
   INIT (waits for auth before loading)
   ------------------------------------------------------------ */
async function initEditor() {
  await loadState();
  wireQuickAdd();
  wireToolbar();
  render();
}

document.addEventListener('studio:authed', initEditor);
// If already authed at load time, studio.js fires the event after DOMContentLoaded
